<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class AddCourseTypeAndAutoGeneratedToCertificates extends Migration
{
    public function up()
    {
        Schema::table('certificates', function (Blueprint $table) {
            $table->string('course_type')->default('physical')->after('trainee_id')->index();
            $table->boolean('auto_generated')->default(false)->after('generated_at');
        });

        // issued_by must become nullable so system-auto-issued certificates
        // don't need a staff author. MySQL requires dropping and re-adding
        // the FK to change nullability on a foreign-keyed column.
        Schema::table('certificates', function (Blueprint $table) {
            $table->dropForeign(['issued_by']);
        });

        Schema::table('certificates', function (Blueprint $table) {
            $table->unsignedInteger('issued_by')->nullable()->change();
            $table->foreign('issued_by')->references('id')->on('users')->onDelete('set null');
        });
    }

    public function down()
    {
        Schema::table('certificates', function (Blueprint $table) {
            $table->dropForeign(['issued_by']);
        });

        Schema::table('certificates', function (Blueprint $table) {
            $table->unsignedInteger('issued_by')->nullable(false)->change();
            $table->foreign('issued_by')->references('id')->on('users')->onDelete('cascade');
        });

        Schema::table('certificates', function (Blueprint $table) {
            $table->dropColumn(['course_type', 'auto_generated']);
        });
    }
}
